---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: chat
  namespace: default
spec:
  replicas: 8
  selector:
    matchLabels:
      app: chat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 34%
      maxUnavailable: 34%
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: phoenix-chat
        image: chat:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
          requests:
            memory: 512Mi
            cpu: ".2"
        env:
        - name: PORT
          value: "4000"
        - name: PHOENIX_CHAT_HOST
          value: "localhost.com"
        - name: DB_URL
          value: ecto://postgres:postgres@db/chat_lv_prod
        - name: SECRET_KEY_BASE
          value: "08WUUMau9/mu1ie/Ee7GMraM3GuPVcvQab6UrnjiQSu1557OXjfkigpR5JZ3khvv"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command: ["elixir"]
        args: ["--name", "chat@$(MY_POD_IP)", "--cookie","secret", "--no-halt", "-S","mix","phx.server"]
---
kind: Service
apiVersion: v1
metadata:
  name: chat
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: chat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 32010
---
kind: Service
apiVersion: v1
metadata:
  name: chat-nodes
  namespace: default
spec:
  clusterIP: None
  selector:
    app: chat
  ports:
    - name: epmd
      port: 4369
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-ws
  namespace: default
spec:
  rules:
  - host: test.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: chat
            port: 
              number: 80
      - path: /ws
        pathType: Prefix
        backend:
          service: 
            name: chat
            port: 
              number: 80